<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;

class Invoice extends Model
{
    use HasFactory;

    /**
     * Status constants
     */
    const STATUS_UNPAID = 'unpaid';
    const STATUS_PAID = 'paid';
    const STATUS_CANCELLED = 'cancelled';
    const STATUS_EXPIRED = 'expired';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'invoice_number',
        'customer_id',
        'package_id',
        'user_id',
        'bill_date',
        'due_date',
        'paid_date',
        'amount',
        'discount',
        'total',
        'status',
        'payment_method',
        'payment_gateway',
        'transaction_id',
        'notes',
        'is_auto_generated',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'bill_date' => 'date',
            'due_date' => 'date',
            'paid_date' => 'date',
            'amount' => 'decimal:2',
            'discount' => 'decimal:2',
            'total' => 'decimal:2',
            'is_auto_generated' => 'boolean',
        ];
    }

    /**
     * Boot the model
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($invoice) {
            if (!$invoice->invoice_number) {
                $invoice->invoice_number = self::generateInvoiceNumber();
            }

            // Calculate total if not set
            if (!$invoice->total && $invoice->amount) {
                $invoice->total = $invoice->amount - ($invoice->discount ?? 0);
            }
        });

        // Update customer's last_payment_date and next_billing_date when invoice is paid
        static::updated(function ($invoice) {
            if ($invoice->wasChanged('status') && $invoice->status === self::STATUS_PAID) {
                $invoice->customer->update([
                    'last_payment_date' => $invoice->paid_date ?? now(),
                    'next_billing_date' => $invoice->due_date->copy()->addDays($invoice->package->validity_days ?? 30),
                ]);
            }
        });
    }

    /**
     * Generate unique invoice number
     */
    public static function generateInvoiceNumber(): string
    {
        $prefix = 'INV-' . date('Ymd');
        $lastInvoice = self::where('invoice_number', 'like', "$prefix%")
            ->orderBy('invoice_number', 'desc')
            ->first();

        if ($lastInvoice) {
            $lastNumber = (int) substr($lastInvoice->invoice_number, -5);
            $newNumber = str_pad($lastNumber + 1, 5, '0', STR_PAD_LEFT);
        } else {
            $newNumber = '00001';
        }

        return $prefix . $newNumber;
    }

    /**
     * Scopes
     */
    public function scopeUnpaid($query)
    {
        return $query->where('status', self::STATUS_UNPAID);
    }

    public function scopePaid($query)
    {
        return $query->where('status', self::STATUS_PAID);
    }

    public function scopeDueDate($query, $days = null)
    {
        $days = $days ?? 0;
        return $query->where('due_date', '<=', now()->addDays($days));
    }

    public function scopeOverdue($query)
    {
        return $query->where('status', self::STATUS_UNPAID)
            ->where('due_date', '<', now());
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Relationships
     */
    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }

    public function package(): BelongsTo
    {
        return $this->belongsTo(Package::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function details(): HasMany
    {
        return $this->hasMany(InvoiceDetail::class);
    }

    public function payments(): HasMany
    {
        return $this->hasMany(Payment::class);
    }

    public function couponUsages(): HasMany
    {
        return $this->hasMany(CouponUsage::class);
    }

    public function activityLogs(): MorphMany
    {
        return $this->morphMany(ActivityLog::class, 'loggable');
    }

    /**
     * Accessors
     */
    public function getIsOverdueAttribute(): bool
    {
        return $this->status === self::STATUS_UNPAID && now()->isAfter($this->due_date);
    }

    public function getIsPaidAttribute(): bool
    {
        return $this->status === self::STATUS_PAID;
    }

    /**
     * Check if invoice can be paid
     */
    public function canBePaid(): bool
    {
        return in_array($this->status, [self::STATUS_UNPAID]);
    }

    /**
     * Mark invoice as paid
     */
    public function markAsPaid(array $paymentData = []): void
    {
        $this->update([
            'status' => self::STATUS_PAID,
            'paid_date' => $paymentData['payment_date'] ?? now(),
            'payment_method' => $paymentData['payment_method'] ?? null,
            'payment_gateway' => $paymentData['payment_gateway'] ?? null,
            'transaction_id' => $paymentData['transaction_id'] ?? null,
        ]);
    }

    /**
     * Mark invoice as cancelled
     */
    public function markAsCancelled(): void
    {
        $this->update(['status' => self::STATUS_CANCELLED]);
    }

    /**
     * Mark invoice as expired
     */
    public function markAsExpired(): void
    {
        $this->update(['status' => self::STATUS_EXPIRED]);
    }

    /**
     * Get formatted amount
     */
    public function getFormattedAmountAttribute(): string
    {
        return 'Rp ' . number_format($this->amount, 0, ',', '.');
    }

    /**
     * Get formatted total
     */
    public function getFormattedTotalAttribute(): string
    {
        return 'Rp ' . number_format($this->total, 0, ',', '.');
    }
}
